###

GET http://localhost:8080/books

### add 1

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "rating": 5
}

### add 2

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "6 The Great Gatsby",
  "author": "6 F. Scott Fitzgerald",
  "rating": 6
}

### add 3

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "3 The Great Gatsby",
  "author": "3 F. Scott Fitzgerald",
  "rating": 3
}

### update 
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "7 The Catcher in the Rye (Updated)",
  "author": "7 J.D. Salinger",
  "rating": 7
}

### delete 
DELETE http://localhost:8080/books/1


### get by ID
GET http://localhost:8080/books/2

