services:

  db:
    container_name: db
    image: public.ecr.aws/docker/library/postgres:16-alpine3.20
    # image: wachira90/postgres:10.15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data/:rw
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : example
      POSTGRES_DB : testdb
    # networks:
    #   pgsql_lan: 

  adminer:
    container_name: adminer
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080
#     networks:
#       pgsql_lan: 

# networks:
#     pgsql_lan:
